site_name: Introduction to Software Security (PKPL)
site_url: https://pkpl.com/
theme:
  name: material
nav:
  - Home: index.md
  - Materials:
    - Threat Dragon:
      - materials/threat-dragon/intro.md
      - materials/threat-dragon/threat-diagram.md